version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_con
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "iram143"
    ports:
      - "3306:3306"
    volumes:  
      - mysql_data:/var/lib/mysql
    networks:
      - todo-net

  app:
    image: iirshad/todo-img:latest   # 👈 tumhari app image
    container_name: todo_con
    ports:
      - "8080:80"   # 👈 browser access
    depends_on:
      - mysql
    networks:
      - todo-net

volumes:
  mysql_data:

networks:
  todo-net:
